server:
  port: 8015

spring:
  application:
    name: CATEGORY
  cloud:
    consul:
      host: localhost
      port: 8500

feign:
  client:
    config:
      PRODUCT:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    com:
      fct:
        feign: debug